const dashboardUser=PrincessApi.requireUser('Customer');
const dashboardStatus=document.querySelector('#dashboard-status');
let dogs=[];
if(dashboardUser){document.querySelector('#dashboard-greeting').textContent=`Welcome back, ${dashboardUser.fullName.split(' ')[0]}.`;loadAll();}

async function loadAll(){
  await Promise.all([loadProfile(),loadDogs(),loadBookings(),loadOwnerIntroduction()]);
  if(new URLSearchParams(location.search).has('booked'))feedback('Your booking request was submitted and is pending confirmation.','success');
}
async function loadOwnerIntroduction(){
  try{const content=await PrincessApi.request('/api/site-content/owner-description');document.querySelector('#dashboard-owner-description').textContent=content.text;}
  catch{document.querySelector('#dashboard-owner-description').textContent='Thoughtful, dependable care for every dog and family.';}
  document.querySelector('#dashboard-owner-photo').addEventListener('error',event=>event.currentTarget.hidden=true,{once:true});
}
async function loadProfile(){
  const user=await PrincessApi.request('/api/users/me');
  document.querySelector('#profile-name').value=user.fullName;document.querySelector('#profile-email').value=user.email;
  document.querySelector('#profile-phone').value=user.phone;document.querySelector('#profile-area').value=user.serviceArea;
  document.querySelector('#profile-address').value=user.serviceAddress;
  const banner=document.querySelector('#approval-banner');const book=document.querySelector('#dashboard-book-button');
  if(user.approvalStatus==='Approved'){banner.hidden=true;book.hidden=false;}
  else{banner.hidden=false;book.hidden=true;banner.className=`approval-banner ${user.approvalStatus.toLowerCase()}`;banner.textContent=user.approvalStatus==='Pending'?'Your account is waiting for Julia’s service-area approval. You can finish your profile and add dogs now.':'Julia could not approve this service area. Update your area/address or contact Julia.';}
  if(user.hasProfilePhoto){const image=document.querySelector('#profile-photo-preview');image.src=await PrincessApi.privateImageUrl('/api/users/me/photo');image.hidden=false;}
}
async function loadDogs(){
  dogs=await PrincessApi.request('/api/dogs');const list=document.querySelector('#dog-list');list.replaceChildren();
  if(!dogs.length)return list.append(empty('No dogs saved yet. Add your first companion.'));
  dogs.forEach(dog=>{const card=document.createElement('article');card.className='mini-card dog-profile-card';if(dog.hasPhoto){const photo=document.createElement('img');photo.className='dog-profile-photo';photo.alt=dog.name;PrincessApi.privateImageUrl(`/api/dogs/${dog.id}/photo`).then(url=>photo.src=url).catch(()=>photo.remove());card.append(photo);}const title=document.createElement('h3');title.textContent=dog.name;const details=document.createElement('p');details.textContent=`${dog.breed||'Breed not specified'}${dog.age!=null?` · Age ${dog.age}`:''}`;card.append(title,details,action('Edit',()=>editDog(dog)),action('Delete',()=>deleteDog(dog.id),'danger'));list.append(card);});
}
async function loadBookings(){const bookings=await PrincessApi.request('/api/bookings');const today=new Date().toISOString().split('T')[0];renderBookings(document.querySelector('#upcoming-bookings'),bookings.filter(item=>(item.endDate||item.date)>=today&&!['Completed','Cancelled','Declined'].includes(item.status)),true);renderBookings(document.querySelector('#previous-bookings'),bookings.filter(item=>(item.endDate||item.date)<today||['Completed','Cancelled','Declined'].includes(item.status)),false);}
function renderBookings(container,items,canCancel){container.replaceChildren();if(!items.length)return container.append(empty('Nothing here yet.'));items.forEach(item=>{const card=document.createElement('article');card.className='appointment-card';card.dataset.status=item.status;const title=document.createElement('h3');title.textContent=`${item.dogName} · ${item.serviceName}`;const meta=document.createElement('p');const nights=item.isOvernightStay?daysBetween(item.date,item.endDate):1;meta.textContent=item.isOvernightStay?`${formatDate(item.date)}–${formatDate(item.endDate)} · ${nights} night${nights===1?'':'s'} · Total $${Number(item.price).toFixed(2)}`:`${formatDate(item.date)} at ${formatTime(item.startTime)} · $${Number(item.price).toFixed(2)}`;const badge=document.createElement('span');badge.className=`status-badge status-${item.status.toLowerCase()}`;badge.textContent=item.status;card.append(title,meta,badge);if(item.specialInstructions){const notes=document.createElement('p');notes.textContent=item.specialInstructions;card.append(notes);}if(canCancel&&['Pending','Confirmed'].includes(item.status))card.append(action('Cancel booking',()=>cancelBooking(item.id),'danger'));container.append(card);});}

document.querySelector('#profile-form').addEventListener('submit',async event=>{event.preventDefault();try{const user=await PrincessApi.request('/api/users/me',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});sessionStorage.setItem('princessDogWalkerUser',JSON.stringify(user));await loadProfile();feedback('Profile saved. Julia will review updated service areas.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#profile-photo-form').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData();data.append('photo',document.querySelector('#profile-photo').files[0]);try{await PrincessApi.request('/api/users/me/photo',{method:'PUT',body:data});event.currentTarget.reset();await loadProfile();feedback('Profile photo updated.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#password-form').addEventListener('submit',async event=>{event.preventDefault();try{await PrincessApi.request('/api/users/me/password',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();feedback('Password updated.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#dog-form').addEventListener('submit',async event=>{event.preventDefault();const id=document.querySelector('#dog-id').value;const data=Object.fromEntries(new FormData(event.currentTarget));data.age=data.age?Number(data.age):null;try{const dog=await PrincessApi.request(`/api/dogs${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});const photo=document.querySelector('#dog-photo').files[0];if(photo){const upload=new FormData();upload.append('photo',photo);await PrincessApi.request(`/api/dogs/${dog.id}/photo`,{method:'PUT',body:upload});}clearDogForm();await loadDogs();feedback('Dog profile saved.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#clear-dog-form').addEventListener('click',clearDogForm);
function editDog(dog){document.querySelector('#dog-id').value=dog.id;document.querySelector('#dog-form-title').textContent=`Edit ${dog.name}`;document.querySelector('#dog-name').value=dog.name;document.querySelector('#dog-breed').value=dog.breed;document.querySelector('#dog-age').value=dog.age??'';document.querySelector('#dog-care').value=dog.careInstructions;document.querySelector('#dog-behavior').value=dog.behavioralNotes;document.querySelector('#dog-medical').value=dog.medicalNotes;document.querySelector('#dog-form').scrollIntoView({behavior:'smooth'});}
function clearDogForm(){document.querySelector('#dog-form').reset();document.querySelector('#dog-id').value='';document.querySelector('#dog-form-title').textContent='Register a dog';}
async function deleteDog(id){if(!confirm('Delete this dog profile?'))return;try{await PrincessApi.request(`/api/dogs/${id}`,{method:'DELETE'});await loadDogs();}catch(error){feedback(error.message,'error');}}
async function cancelBooking(id){if(!confirm('Cancel this upcoming booking?'))return;try{await PrincessApi.request(`/api/bookings/${id}/cancel`,{method:'PUT'});await loadBookings();feedback('Booking cancelled.','success');}catch(error){feedback(error.message,'error');}}
function action(text,handler,extra=''){const button=document.createElement('button');button.className=`link-button ${extra}`;button.type='button';button.textContent=text;button.addEventListener('click',handler);return button;}
function feedback(text,type){dashboardStatus.textContent=text;dashboardStatus.className=`form-status ${type}`;dashboardStatus.scrollIntoView({behavior:'smooth'});}function empty(text){const node=document.createElement('div');node.className='empty-state';node.textContent=text;return node;}function formatDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}function formatTime(value){const[h,m]=value.split(':');return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m));}function daysBetween(start,end){return Math.max(1,Math.round((new Date(`${end}T00:00:00Z`)-new Date(`${start}T00:00:00Z`))/86400000));}
