const dashboardUser = PrincessApi.requireUser('Customer');
const dashboardStatus = document.querySelector('#dashboard-status');
let dogs = [];
if (dashboardUser) { document.querySelector('#dashboard-greeting').textContent = `Welcome back, ${dashboardUser.fullName.split(' ')[0]}.`; loadAll(); }
async function loadAll() { await Promise.all([loadProfile(), loadDogs(), loadBookings()]); if (new URLSearchParams(location.search).has('booked')) feedback('Your booking request was submitted and is pending confirmation.', 'success'); }
async function loadProfile() { const user = await PrincessApi.request('/api/users/me'); document.querySelector('#profile-name').value = user.fullName; document.querySelector('#profile-email').value = user.email; document.querySelector('#profile-phone').value = user.phone; }
async function loadDogs() { dogs = await PrincessApi.request('/api/dogs'); const list = document.querySelector('#dog-list'); list.replaceChildren(); if (!dogs.length) list.append(empty('No dogs saved yet. Add your first companion.')); dogs.forEach(dog => { const card = document.createElement('article'); card.className='mini-card'; const title=document.createElement('h3'); title.textContent=dog.name; const details=document.createElement('p'); details.textContent=`${dog.breed || 'Breed not specified'}${dog.age != null ? ` · Age ${dog.age}` : ''}`; const edit=document.createElement('button'); edit.className='link-button'; edit.textContent='Edit'; edit.addEventListener('click',()=>editDog(dog)); const del=document.createElement('button'); del.className='link-button danger'; del.textContent='Delete'; del.addEventListener('click',()=>deleteDog(dog.id)); card.append(title,details,edit,del); list.append(card); }); }
async function loadBookings() { const bookings = await PrincessApi.request('/api/bookings'); const today=new Date().toISOString().split('T')[0]; renderBookings(document.querySelector('#upcoming-bookings'), bookings.filter(item=>item.date>=today&&!['Completed','Cancelled','Declined'].includes(item.status)), true); renderBookings(document.querySelector('#previous-bookings'), bookings.filter(item=>item.date<today||['Completed','Cancelled','Declined'].includes(item.status)), false); }
function renderBookings(container, items, canCancel) { container.replaceChildren(); if(!items.length)return container.append(empty('Nothing here yet.')); items.forEach(item=>{const card=document.createElement('article');card.className='appointment-card';card.dataset.status=item.status;const title=document.createElement('h3');title.textContent=`${item.dogName} · ${item.serviceName}`;const meta=document.createElement('p');meta.textContent=`${formatDate(item.date)} at ${formatTime(item.startTime)} · $${Number(item.price).toFixed(2)}`;const badge=document.createElement('span');badge.className=`status-badge status-${item.status.toLowerCase()}`;badge.textContent=item.status;card.append(title,meta,badge);if(item.specialInstructions){const notes=document.createElement('p');notes.textContent=item.specialInstructions;card.append(notes);}if(canCancel&&['Pending','Confirmed'].includes(item.status)){const button=document.createElement('button');button.className='link-button danger';button.textContent='Cancel booking';button.addEventListener('click',()=>cancelBooking(item.id));card.append(button);}container.append(card);}); }
document.querySelector('#profile-form').addEventListener('submit',async event=>{event.preventDefault();try{const user=await PrincessApi.request('/api/users/me',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});sessionStorage.setItem('princessDogWalkerUser',JSON.stringify(user));feedback('Profile saved.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#dog-form').addEventListener('submit',async event=>{event.preventDefault();const id=document.querySelector('#dog-id').value;const data=Object.fromEntries(new FormData(event.currentTarget));data.age=data.age?Number(data.age):null;try{await PrincessApi.request(`/api/dogs${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});clearDogForm();await loadDogs();feedback('Dog profile saved.','success');}catch(error){feedback(error.message,'error');}});
document.querySelector('#clear-dog-form').addEventListener('click',clearDogForm);
function editDog(dog){document.querySelector('#dog-id').value=dog.id;document.querySelector('#dog-form-title').textContent=`Edit ${dog.name}`;document.querySelector('#dog-name').value=dog.name;document.querySelector('#dog-breed').value=dog.breed;document.querySelector('#dog-age').value=dog.age??'';document.querySelector('#dog-care').value=dog.careInstructions;document.querySelector('#dog-behavior').value=dog.behavioralNotes;document.querySelector('#dog-medical').value=dog.medicalNotes;document.querySelector('#dog-form').scrollIntoView({behavior:'smooth'});}
function clearDogForm(){document.querySelector('#dog-form').reset();document.querySelector('#dog-id').value='';document.querySelector('#dog-form-title').textContent='Add a dog';}
async function deleteDog(id){if(!confirm('Delete this dog profile?'))return;try{await PrincessApi.request(`/api/dogs/${id}`,{method:'DELETE'});await loadDogs();}catch(error){feedback(error.message,'error');}}
async function cancelBooking(id){if(!confirm('Cancel this upcoming booking?'))return;try{await PrincessApi.request(`/api/bookings/${id}/cancel`,{method:'PUT'});await loadBookings();feedback('Booking cancelled.','success');}catch(error){feedback(error.message,'error');}}
function feedback(text,type){dashboardStatus.textContent=text;dashboardStatus.className=`form-status ${type}`;dashboardStatus.scrollIntoView({behavior:'smooth'});}function empty(text){const node=document.createElement('div');node.className='empty-state';node.textContent=text;return node;}function formatDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}function formatTime(value){const[h,m]=value.split(':');return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m));}
