const ownerUser = PrincessApi.requireUser('Owner');
const ownerStatus = document.querySelector('#owner-status');
let ownerServices=[]; let ownerCustomers=[]; let ownerBookings=[]; let rules=[];
let ownerCalendarDate=new Date();
document.querySelector('#refresh-owner').addEventListener('click',loadOwner);
async function loadOwner(){try{await Promise.all([loadBookings(),loadServices(),loadRules(),loadCustomers()]);renderOwnerCalendar();}catch(error){feedback(error.message,'error');}}
async function loadBookings(){ownerBookings=await PrincessApi.request('/api/bookings/admin');const list=document.querySelector('#owner-booking-list');list.replaceChildren();if(!ownerBookings.length)return list.append(empty('No bookings yet.'));ownerBookings.forEach(item=>{const card=document.createElement('article');card.className=`appointment-card ${serviceColorClass(item.serviceId)}`;card.dataset.status=item.status;card.style.borderLeftColor='var(--booking-color)';const head=document.createElement('div');head.className='appointment-head';const copy=document.createElement('div');const title=document.createElement('h3');title.textContent=`${item.dogName} · ${item.serviceName}`;const meta=document.createElement('p');meta.textContent=`${formatDate(item.date)} at ${formatTime(item.startTime)} · ${item.customerName} · ${item.customerEmail}`;copy.append(title,meta);const select=document.createElement('select');select.setAttribute('aria-label',`Status for ${item.dogName}`);['Pending','Confirmed','Completed','Cancelled','Declined'].forEach(status=>{const option=new Option(status,status,status===item.status,status===item.status);select.add(option);});select.addEventListener('change',()=>changeBookingStatus(item.id,select));head.append(copy,select);card.append(head);if(item.specialInstructions){const notes=document.createElement('p');notes.textContent=`Instructions: ${item.specialInstructions}`;card.append(notes);}list.append(card);});renderOwnerCalendar();}
async function changeBookingStatus(id,select){select.disabled=true;try{await PrincessApi.request(`/api/bookings/${id}/status`,{method:'PUT',body:JSON.stringify({status:select.value})});feedback('Booking status updated.','success');await loadBookings();}catch(error){feedback(error.message,'error');await loadBookings();}finally{select.disabled=false;}}
async function loadServices(){ownerServices=await PrincessApi.request('/api/services?includeInactive=true');const list=document.querySelector('#owner-service-list');list.replaceChildren();ownerServices.forEach(service=>{const card=mini(`${service.name}${service.isActive?'':' · Inactive'}`,`${service.durationMinutes} min · $${Number(service.price).toFixed(2)}\n${service.description}`);card.append(action('Edit',()=>editService(service)),action('Delete',()=>deleteService(service.id),'danger'));list.append(card);});const select=document.querySelector('#owner-book-service');const selected=select.value;select.innerHTML='<option value="">Choose a service</option>';ownerServices.filter(service=>service.isActive).forEach(service=>select.add(new Option(`${service.name} · $${Number(service.price).toFixed(2)}`,service.id)));select.value=selected;renderOwnerCalendar();}
document.querySelector('#service-form').addEventListener('submit',async event=>{event.preventDefault();const id=document.querySelector('#service-id').value;const data=Object.fromEntries(new FormData(event.currentTarget));data.durationMinutes=Number(data.durationMinutes);data.price=Number(data.price);data.isActive=document.querySelector('#service-active').checked;try{await PrincessApi.request(`/api/services${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});clearService();await loadServices();feedback('Service saved and public listings updated.','success');}catch(error){feedback(error.message,'error');}});
function editService(item){document.querySelector('#service-id').value=item.id;document.querySelector('#service-form-title').textContent=`Edit ${item.name}`;document.querySelector('#service-name').value=item.name;document.querySelector('#service-description').value=item.description;document.querySelector('#service-duration').value=item.durationMinutes;document.querySelector('#service-price').value=item.price;document.querySelector('#service-active').checked=item.isActive;document.querySelector('#service-form').scrollIntoView({behavior:'smooth'});}function clearService(){document.querySelector('#service-form').reset();document.querySelector('#service-id').value='';document.querySelector('#service-form-title').textContent='Add service';document.querySelector('#service-active').checked=true;}document.querySelector('#clear-service').addEventListener('click',clearService);async function deleteService(id){if(!confirm('Delete this service? Services with booking history should be disabled instead.'))return;try{await PrincessApi.request(`/api/services/${id}`,{method:'DELETE'});await loadServices();}catch(error){feedback(error.message,'error');}}
document.querySelector('#new-service').addEventListener('click',()=>{clearService();document.querySelector('#service-form').scrollIntoView({behavior:'smooth'});document.querySelector('#service-name').focus();});
const ownerBookCustomer=document.querySelector('#owner-book-customer');
const ownerBookDog=document.querySelector('#owner-book-dog');
const ownerBookService=document.querySelector('#owner-book-service');
const ownerBookDate=document.querySelector('#owner-book-date');
const ownerBookTime=document.querySelector('#owner-book-time');
const bookingToday=new Date();
ownerBookDate.min=new Date(bookingToday.getTime()-bookingToday.getTimezoneOffset()*60000).toISOString().split('T')[0];
ownerBookDate.value=ownerBookDate.min;
ownerBookCustomer.addEventListener('change',populateOwnerDogs);
ownerBookService.addEventListener('change',loadOwnerBookingTimes);
ownerBookDate.addEventListener('change',loadOwnerBookingTimes);
function populateOwnerDogs(){const customer=ownerCustomers.find(item=>item.id===ownerBookCustomer.value);ownerBookDog.innerHTML='<option value="">Choose a dog</option>';(customer?.dogs||[]).forEach(dog=>ownerBookDog.add(new Option(`${dog.name}${dog.breed?` · ${dog.breed}`:''}`,dog.id)));ownerBookDog.disabled=!customer?.dogs?.length;if(customer&&!customer.dogs.length)ownerBookDog.innerHTML='<option value="">This customer has no saved dogs</option>';}
async function loadOwnerBookingTimes(){ownerBookTime.disabled=true;ownerBookTime.innerHTML='<option value="">Choose a service and date</option>';if(!ownerBookService.value||!ownerBookDate.value)return;ownerBookTime.innerHTML='<option value="">Checking open times…</option>';try{const slots=await PrincessApi.request(`/api/availability/slots?from=${ownerBookDate.value}&to=${ownerBookDate.value}&serviceId=${ownerBookService.value}`);ownerBookTime.innerHTML='<option value="">Choose an open time</option>';slots.forEach(slot=>ownerBookTime.add(new Option(formatTime(slot.startTime),slot.startTime)));ownerBookTime.disabled=!slots.length;if(!slots.length)ownerBookTime.innerHTML='<option value="">No open times on this date</option>';}catch(error){ownerBookTime.innerHTML='<option value="">Could not load times</option>';feedback(error.message,'error');}}
document.querySelector('#owner-booking-form').addEventListener('submit',async event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;const data={customerId:ownerBookCustomer.value,dogId:Number(ownerBookDog.value),serviceId:Number(ownerBookService.value),date:ownerBookDate.value,startTime:ownerBookTime.value,specialInstructions:document.querySelector('#owner-book-notes').value};try{await PrincessApi.request('/api/bookings/admin',{method:'POST',body:JSON.stringify(data)});document.querySelector('#owner-book-notes').value='';await loadBookings();await loadOwnerBookingTimes();feedback('Confirmed booking added for the customer.','success');}catch(error){feedback(error.message,'error');await loadOwnerBookingTimes();}});
document.querySelector('#owner-calendar-prev').addEventListener('click',()=>{ownerCalendarDate=new Date(ownerCalendarDate.getFullYear(),ownerCalendarDate.getMonth()-1,1);renderOwnerCalendar();});
document.querySelector('#owner-calendar-next').addEventListener('click',()=>{ownerCalendarDate=new Date(ownerCalendarDate.getFullYear(),ownerCalendarDate.getMonth()+1,1);renderOwnerCalendar();});
function serviceColorClass(serviceId){const index=ownerServices.findIndex(service=>service.id===serviceId);return `booking-color-${(index<0?Number(serviceId):index)%6}`;}
function renderOwnerCalendar(){const calendar=document.querySelector('#owner-month-calendar');const legend=document.querySelector('#booking-legend');if(!calendar||!legend)return;const year=ownerCalendarDate.getFullYear();const month=ownerCalendarDate.getMonth();document.querySelector('#owner-calendar-month').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(year,month,1));calendar.replaceChildren();['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(day=>{const label=document.createElement('div');label.className='calendar-weekday';label.textContent=day;calendar.append(label);});for(let blank=0;blank<new Date(year,month,1).getDay();blank+=1){const cell=document.createElement('div');cell.className='owner-calendar-day is-empty';calendar.append(cell);}const daysInMonth=new Date(year,month+1,0).getDate();for(let day=1;day<=daysInMonth;day+=1){const date=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const cell=document.createElement('div');cell.className='owner-calendar-day';const number=document.createElement('span');number.className='calendar-day-number';number.textContent=day;cell.append(number);ownerBookings.filter(item=>item.date===date&&!['Cancelled','Declined'].includes(item.status)).forEach(item=>{const event=document.createElement('div');event.className=`owner-calendar-event ${serviceColorClass(item.serviceId)}`;event.textContent=`${formatTime(item.startTime)} ${item.dogName}`;event.title=`${item.serviceName} · ${item.customerName} · ${item.status}`;cell.append(event);});calendar.append(cell);}const visibleServices=new Map();ownerBookings.filter(item=>{const date=new Date(`${item.date}T00:00:00`);return date.getFullYear()===year&&date.getMonth()===month&&!['Cancelled','Declined'].includes(item.status);}).forEach(item=>visibleServices.set(item.serviceId,item.serviceName));legend.replaceChildren();if(!visibleServices.size){const note=document.createElement('span');note.className='hint';note.textContent='No bookings this month.';legend.append(note);}visibleServices.forEach((name,id)=>{const item=document.createElement('span');item.className=`legend-item ${serviceColorClass(id)}`;const dot=document.createElement('span');dot.className='legend-dot';item.append(dot,document.createTextNode(name));legend.append(item);});}
const ruleDate=document.querySelector('#rule-date');
const ownerToday=new Date();
const weekdayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
ruleDate.min=new Date(ownerToday.getTime()-ownerToday.getTimezoneOffset()*60000).toISOString().split('T')[0];
ruleDate.value=ruleDate.min;
async function loadRules(){rules=await PrincessApi.request('/api/availability');const list=document.querySelector('#availability-rule-list');list.replaceChildren();if(!rules.length)list.append(empty('Nothing is blocked. Julia is available every day and night.'));rules.forEach(rule=>{const allDay=rule.startTime.startsWith('00:00')&&rule.endTime.startsWith('23:59');const when=allDay?'Entire day':`${formatTime(rule.startTime)}–${formatTime(rule.endTime)}`;const scope=rule.specificDate?formatDate(rule.specificDate):`Every ${weekdayNames[Number(rule.dayOfWeek)]}`;const card=mini(scope,`${when}${rule.notes?`\n${rule.notes}`:''}`);if(rule.specificDate)card.append(action('Edit',()=>editRule(rule)));card.append(action('Make available',()=>deleteRule(rule.id),'danger'));list.append(card);});}
document.querySelector('#rule-block-type').addEventListener('change',toggleRuleTimes);function toggleRuleTimes(){const timed=document.querySelector('#rule-block-type').value==='hours';document.querySelector('#rule-time-fields').hidden=!timed;document.querySelector('#rule-start').required=timed;document.querySelector('#rule-end').required=timed;}
document.querySelector('#availability-rule-form').addEventListener('submit',async event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;const id=document.querySelector('#rule-id').value;const allDay=document.querySelector('#rule-block-type').value==='day';const data={dayOfWeek:null,specificDate:ruleDate.value,startTime:allDay?'00:00':document.querySelector('#rule-start').value,endTime:allDay?'23:59':document.querySelector('#rule-end').value,isAvailable:false,notes:document.querySelector('#rule-notes').value};try{await PrincessApi.request(`/api/availability${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});clearRule();await loadRules();feedback('Unavailable time saved. Customers will not be offered this period.','success');}catch(error){feedback(error.message,'error');}});
function editRule(rule){document.querySelector('#rule-id').value=rule.id;document.querySelector('#rule-form-title').textContent='Edit unavailable time';ruleDate.value=rule.specificDate||'';const allDay=rule.startTime.startsWith('00:00')&&rule.endTime.startsWith('23:59');document.querySelector('#rule-block-type').value=allDay?'day':'hours';document.querySelector('#rule-start').value=rule.startTime;document.querySelector('#rule-end').value=rule.endTime;document.querySelector('#rule-notes').value=rule.notes;toggleRuleTimes();document.querySelector('#availability-rule-form').scrollIntoView({behavior:'smooth'});}function clearRule(){document.querySelector('#availability-rule-form').reset();ruleDate.value=ruleDate.min;document.querySelector('#rule-id').value='';document.querySelector('#rule-form-title').textContent='Block an unavailable date';toggleRuleTimes();}document.querySelector('#clear-rule').addEventListener('click',clearRule);async function deleteRule(id){if(!confirm('Make this date and time available again?'))return;try{await PrincessApi.request(`/api/availability/${id}`,{method:'DELETE'});await loadRules();feedback('That date and time are available again.','success');}catch(error){feedback(error.message,'error');}}
async function loadCustomers(){ownerCustomers=await PrincessApi.request('/api/users/customers');const list=document.querySelector('#owner-customer-list');const selected=ownerBookCustomer.value;list.replaceChildren();ownerBookCustomer.innerHTML='<option value="">Choose a customer</option>';ownerCustomers.forEach(customer=>ownerBookCustomer.add(new Option(`${customer.fullName} · ${customer.email}`,customer.id)));ownerBookCustomer.value=selected;populateOwnerDogs();if(!ownerCustomers.length)return list.append(empty('No registered customers yet.'));ownerCustomers.forEach(customer=>{const dogs=customer.dogs.map(dog=>`${dog.name}${dog.breed?` (${dog.breed})`:''}`).join(', ')||'No dogs saved';list.append(mini(customer.fullName,`${customer.email} · ${customer.phone}\nDogs: ${dogs}`));});}
if(ownerUser)loadOwner();
function mini(titleText,bodyText){const card=document.createElement('article');card.className='mini-card';const title=document.createElement('h3');title.textContent=titleText;const body=document.createElement('p');body.textContent=bodyText;body.style.whiteSpace='pre-line';card.append(title,body);return card;}function action(text,handler,extra=''){const button=document.createElement('button');button.className=`link-button ${extra}`;button.type='button';button.textContent=text;button.addEventListener('click',handler);return button;}function empty(text){const node=document.createElement('div');node.className='empty-state';node.textContent=text;return node;}function feedback(text,type){ownerStatus.textContent=text;ownerStatus.className=`form-status ${type}`;ownerStatus.scrollIntoView({behavior:'smooth'});}function formatDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}function formatTime(value){const[h,m]=value.split(':');return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m));}
