const ownerUser = PrincessApi.requireUser('Owner');
const ownerStatus = document.querySelector('#owner-status');
let ownerServices=[]; let rules=[];
if(ownerUser) loadOwner();
document.querySelector('#refresh-owner').addEventListener('click',loadOwner);
async function loadOwner(){try{await Promise.all([loadBookings(),loadServices(),loadRules(),loadCustomers()]);}catch(error){feedback(error.message,'error');}}
async function loadBookings(){const items=await PrincessApi.request('/api/bookings/admin');const list=document.querySelector('#owner-booking-list');list.replaceChildren();if(!items.length)return list.append(empty('No bookings yet.'));items.forEach(item=>{const card=document.createElement('article');card.className='appointment-card';card.dataset.status=item.status;const head=document.createElement('div');head.className='appointment-head';const copy=document.createElement('div');const title=document.createElement('h3');title.textContent=`${item.dogName} · ${item.serviceName}`;const meta=document.createElement('p');meta.textContent=`${formatDate(item.date)} at ${formatTime(item.startTime)} · ${item.customerName} · ${item.customerEmail}`;copy.append(title,meta);const select=document.createElement('select');select.setAttribute('aria-label',`Status for ${item.dogName}`);['Pending','Confirmed','Completed','Cancelled','Declined'].forEach(status=>{const option=new Option(status,status,status===item.status,status===item.status);select.add(option);});select.addEventListener('change',()=>changeBookingStatus(item.id,select));head.append(copy,select);card.append(head);if(item.specialInstructions){const notes=document.createElement('p');notes.textContent=`Instructions: ${item.specialInstructions}`;card.append(notes);}list.append(card);});}
async function changeBookingStatus(id,select){select.disabled=true;try{await PrincessApi.request(`/api/bookings/${id}/status`,{method:'PUT',body:JSON.stringify({status:select.value})});feedback('Booking status updated.','success');await loadBookings();}catch(error){feedback(error.message,'error');await loadBookings();}finally{select.disabled=false;}}
async function loadServices(){ownerServices=await PrincessApi.request('/api/services?includeInactive=true');const list=document.querySelector('#owner-service-list');list.replaceChildren();ownerServices.forEach(service=>{const card=mini(`${service.name}${service.isActive?'':' · Inactive'}`,`${service.durationMinutes} min · $${Number(service.price).toFixed(2)}\n${service.description}`);card.append(action('Edit',()=>editService(service)),action('Delete',()=>deleteService(service.id),'danger'));list.append(card);});}
document.querySelector('#service-form').addEventListener('submit',async event=>{event.preventDefault();const id=document.querySelector('#service-id').value;const data=Object.fromEntries(new FormData(event.currentTarget));data.durationMinutes=Number(data.durationMinutes);data.price=Number(data.price);data.isActive=document.querySelector('#service-active').checked;try{await PrincessApi.request(`/api/services${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});clearService();await loadServices();feedback('Service saved and public listings updated.','success');}catch(error){feedback(error.message,'error');}});
function editService(item){document.querySelector('#service-id').value=item.id;document.querySelector('#service-form-title').textContent=`Edit ${item.name}`;document.querySelector('#service-name').value=item.name;document.querySelector('#service-description').value=item.description;document.querySelector('#service-duration').value=item.durationMinutes;document.querySelector('#service-price').value=item.price;document.querySelector('#service-active').checked=item.isActive;document.querySelector('#service-form').scrollIntoView({behavior:'smooth'});}function clearService(){document.querySelector('#service-form').reset();document.querySelector('#service-id').value='';document.querySelector('#service-form-title').textContent='Add service';document.querySelector('#service-active').checked=true;}document.querySelector('#clear-service').addEventListener('click',clearService);async function deleteService(id){if(!confirm('Delete this service? Services with booking history should be disabled instead.'))return;try{await PrincessApi.request(`/api/services/${id}`,{method:'DELETE'});await loadServices();}catch(error){feedback(error.message,'error');}}
const weekdayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
async function loadRules(){rules=await PrincessApi.request('/api/availability');const list=document.querySelector('#availability-rule-list');list.replaceChildren();if(!rules.length)list.append(empty('No availability rules yet. Add working hours to open booking slots.'));rules.forEach(rule=>{const scope=rule.specificDate?formatDate(rule.specificDate):(typeof rule.dayOfWeek==='number'?weekdayNames[rule.dayOfWeek]:rule.dayOfWeek);const card=mini(`${scope} · ${rule.isAvailable?'Available':'Blocked'}`,`${formatTime(rule.startTime)}–${formatTime(rule.endTime)}${rule.notes?`\n${rule.notes}`:''}`);card.append(action('Edit',()=>editRule(rule)),action('Remove',()=>deleteRule(rule.id),'danger'));list.append(card);});}
document.querySelector('#rule-scope').addEventListener('change',toggleRuleScope);function toggleRuleScope(){const dated=document.querySelector('#rule-scope').value==='date';document.querySelector('#date-field').hidden=!dated;document.querySelector('#weekday-field').hidden=dated;document.querySelector('#rule-date').required=dated;}
document.querySelector('#availability-rule-form').addEventListener('submit',async event=>{event.preventDefault();const id=document.querySelector('#rule-id').value;const dated=document.querySelector('#rule-scope').value==='date';const data={dayOfWeek:dated?null:Number(document.querySelector('#rule-weekday').value),specificDate:dated?document.querySelector('#rule-date').value:null,startTime:document.querySelector('#rule-start').value,endTime:document.querySelector('#rule-end').value,isAvailable:document.querySelector('#rule-mode').value==='true',notes:document.querySelector('#rule-notes').value};try{await PrincessApi.request(`/api/availability${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(data)});clearRule();await loadRules();feedback('Availability updated. Customer slots now reflect this rule.','success');}catch(error){feedback(error.message,'error');}});
function editRule(rule){document.querySelector('#rule-id').value=rule.id;document.querySelector('#rule-form-title').textContent='Edit availability rule';document.querySelector('#rule-scope').value=rule.specificDate?'date':'weekday';toggleRuleScope();document.querySelector('#rule-weekday').value=typeof rule.dayOfWeek==='number'?rule.dayOfWeek:Math.max(0,weekdayNames.indexOf(rule.dayOfWeek));document.querySelector('#rule-date').value=rule.specificDate||'';document.querySelector('#rule-start').value=rule.startTime;document.querySelector('#rule-end').value=rule.endTime;document.querySelector('#rule-mode').value=String(rule.isAvailable);document.querySelector('#rule-notes').value=rule.notes;document.querySelector('#availability-rule-form').scrollIntoView({behavior:'smooth'});}function clearRule(){document.querySelector('#availability-rule-form').reset();document.querySelector('#rule-id').value='';document.querySelector('#rule-form-title').textContent='Add availability rule';toggleRuleScope();}document.querySelector('#clear-rule').addEventListener('click',clearRule);async function deleteRule(id){if(!confirm('Remove this availability rule?'))return;try{await PrincessApi.request(`/api/availability/${id}`,{method:'DELETE'});await loadRules();}catch(error){feedback(error.message,'error');}}
async function loadCustomers(){const customers=await PrincessApi.request('/api/users/customers');const list=document.querySelector('#owner-customer-list');list.replaceChildren();if(!customers.length)return list.append(empty('No registered customers yet.'));customers.forEach(customer=>{const dogs=customer.dogs.map(dog=>`${dog.name}${dog.breed?` (${dog.breed})`:''}`).join(', ')||'No dogs saved';list.append(mini(customer.fullName,`${customer.email} · ${customer.phone}\nDogs: ${dogs}`));});}
function mini(titleText,bodyText){const card=document.createElement('article');card.className='mini-card';const title=document.createElement('h3');title.textContent=titleText;const body=document.createElement('p');body.textContent=bodyText;body.style.whiteSpace='pre-line';card.append(title,body);return card;}function action(text,handler,extra=''){const button=document.createElement('button');button.className=`link-button ${extra}`;button.type='button';button.textContent=text;button.addEventListener('click',handler);return button;}function empty(text){const node=document.createElement('div');node.className='empty-state';node.textContent=text;return node;}function feedback(text,type){ownerStatus.textContent=text;ownerStatus.className=`form-status ${type}`;ownerStatus.scrollIntoView({behavior:'smooth'});}function formatDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}function formatTime(value){const[h,m]=value.split(':');return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m));}
